### ISSUE TITLE
No completions for packages in the import block

### ISSUE THREAD

**Issue by ramya-rao-a** [mdempsky/gocode#38] opened 2018-07-16 00:32 UTC
When using nsf/gocode, we get completions for packages in the import block. The same isn't available when using mdempsky/gocode.

For example: In the below code, trigger completions from inside the `""` in the import block

```
package main

import (
	""
)

func main() {
	
}
```

nsf/gocode gives:

<img width="672" alt="screen shot 2018-07-15 at 5 31 48 pm" src="https://user-images.githubusercontent.com/16890566/42739951-ef2ddf1e-8854-11e8-8225-191f42a46f9d.png">

mdempsky/gocode gives:
<img width="1024" alt="screen shot 2018-07-15 at 5 30 41 pm" src="https://user-images.githubusercontent.com/16890566/42739953-f9789194-8854-11e8-8cfc-e5f940de25a7.png">

**Comment by scottjbarr** [comment] 2018-08-23 21:46
That won't compile, so I personally wouldn't expect it to work.

**Comment by hellupline** [comment] 2018-09-02 05:20
the issue is not the dummy code that cant compile, 
its a missing feature from nsf/gocode which mdempsky/gocode doesn't have

**Comment by mohanson** [comment] 2018-09-03 03:02
Steps to Reproduce:
1. vi main.go
2. input "net/" can't get import suggestions(in "nsf/gocode", "net/http" will be suggested)

**Comment by segevfiner** [comment] 2018-12-30 09:08
Related commits from `nsf/gocode`: https://github.com/nsf/gocode/commit/9e6ef41d7b072f389a4675b0f7718dedb232cb96 and https://github.com/nsf/gocode/commit/40385eba48ae61394e5d2935b1e5c7130fa9b46b.

**Comment by stamblerre** [comment] 2019-01-02 19:01
I'm happy to review PRs for this feature, but I don't think I will have time to implement it myself.

**Comment by JackieLs** [comment] 2019-01-04 03:32
Look forward to this feature ......

**Comment by segevfiner** [comment] 2019-01-06 23:41
As I said, I think this exists in nsf/gocode and I pointed to the relevant commits in a previous comment. So instead of implementing, I think this just needs merging/cherry-picking. There might be other such bug fixes/features in nsf/gocode that were contributed to it before this fork became the recommended version.

**Comment by jsfaint** [comment] 2019-01-09 10:28
@segevfiner I'm looking for this feature too.
But it looks the code structure between these two repo is totally different since long time ago.
The commit can't be used directly.

**Comment by stamblerre** [comment] 2019-12-02 07:34
This is something we are tracking for `gopls` in https://github.com/golang/go/issues/35877. Since this repository is in maintenance mode, it won't be implemented here.

**Closed as completed by stamblerre** 2019-12-02 07:34 UTC
Labels: enhancement, help wanted, good first issue
