### ISSUE TITLE
missing dependency 

### ISSUE THREAD

**Issue by ruivapps** [mdempsky/gocode#113] opened 2019-05-11 00:01 UTC
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?
go version go1.12.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
osx 10.14.4

### What is the debug output of `gocode`?
N/A

Run `gocode close` and then run `gocode -s -debug` to restart gocode in debug mode. 
Try to complete once again from your editor, and paste the output printed by gocode here.
N/A

### What (client-side) flags are you passing into `gocode`?
N/A

Please note here if you are using `-source`, `-builtin`, `-ignore-case`, `-unimported-packages`, or `-fallback-to-source`.

### What editor are using?
N/A

just did a fresh installation of go, running 
`go get -u github.com/mdempsky/gocode`
`go get -u all`
received errors about can not find `golang.org/x/text`

`go get -u golang.org/x/text`  will fix it.

**Comment by stamblerre** [comment] 2019-12-02 07:02
I am not able to reproduce this issue, and I don't believe that this project depends on `golang.org/x/text`. Closing.

**Closed as completed by stamblerre** 2019-12-02 07:02 UTC
